# generated by datamodel-codegen:
#   filename:  schema.yml
#   timestamp: 2026-10-04T09:16:08+00:00

from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from enum import StrEnum
from typing import Annotated, Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class AktualnosciComment(BaseModel):
    id: int
    content: str
    author: Annotated[int | None, Field(...)]
    author_name: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class AktualnosciCommentCreateRequest(BaseModel):
    content: Annotated[str, Field(min_length=1)]


class ExternalLink(RootModel[AnyUrl | None]):
    root: AnyUrl | None = None


class ExternalLink1(RootModel[str | None]):
    root: Annotated[str | None, Field(max_length=0)] = None


class AktualnosciThread(BaseModel):
    id: int
    title: Annotated[str | None, Field(max_length=200)] = None
    content: str
    external_link: ExternalLink | ExternalLink1 | None = None
    author: Annotated[int | None, Field(...)]
    author_name: str
    created_at: AwareDatetime
    updated_at: AwareDatetime
    comments: list[AktualnosciComment]


class ExternalLink2(RootModel[AnyUrl | None]):
    root: AnyUrl | None = None


class ExternalLink3(RootModel[str | None]):
    root: Annotated[str | None, Field(max_length=0)] = None


class AktualnosciThreadUpdateRequest(BaseModel):
    title: Annotated[str | None, Field(max_length=200)] = None
    content: Annotated[str, Field(min_length=1)]
    external_link: ExternalLink2 | ExternalLink3 | None = None


class Attachment(BaseModel):
    id: int
    file: AnyUrl
    uploaded_at: AwareDatetime
    club_id: Annotated[
        int | None, Field(ge=-9223372036854775808, le=9223372036854775807)
    ] = None


class AttachmentRequest(BaseModel):
    file: bytes
    club_id: Annotated[
        int | None, Field(ge=-9223372036854775808, le=9223372036854775807)
    ] = None


class ClubCalendarEvent(BaseModel):
    id: int
    title: Annotated[str, Field(max_length=160)]
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    start_time: AwareDatetime
    end_time: AwareDatetime
    all_day: bool | None = None
    created_by: Annotated[int | None, Field(...)]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ClubCalendarEventRequest(BaseModel):
    title: Annotated[str, Field(max_length=160, min_length=1)]
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    start_time: AwareDatetime
    end_time: AwareDatetime
    all_day: bool | None = None


class ClubPhoto(BaseModel):
    id: int
    image: AnyUrl
    image_url: str
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    created_at: AwareDatetime


class ClubPhotoRequest(BaseModel):
    image: bytes
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None


class Website(RootModel[AnyUrl | None]):
    root: Annotated[AnyUrl | None, Field(title='Strona klubu')] = None


class Website1(RootModel[str | None]):
    root: Annotated[str | None, Field(max_length=0, title='Strona klubu')] = None


class ClubProfile(BaseModel):
    id: int
    logo: AnyUrl | None = None
    photos: list[ClubPhoto]
    opening_time_mon: time | None = None
    closing_time_mon: time | None = None
    opening_time_tue: time | None = None
    closing_time_tue: time | None = None
    opening_time_wed: time | None = None
    closing_time_wed: time | None = None
    opening_time_thu: time | None = None
    closing_time_thu: time | None = None
    opening_time_fri: time | None = None
    closing_time_fri: time | None = None
    opening_time_sat: time | None = None
    closing_time_sat: time | None = None
    opening_time_sun: time | None = None
    closing_time_sun: time | None = None
    current_storage_usage_mb: str
    remaining_storage_mb: str
    storage_limit_enabled: str
    current_users_count: str
    remaining_user_slots: str
    user_limit_enabled: str
    effective_user_limit: str
    effective_storage_limit_mb: str
    name: Annotated[str, Field(max_length=100, title='Nazwa klubu')]
    user_limit: Annotated[
        int | None,
        Field(
            description='Maksymalna liczba użytkowników klubu. Brak wartości oznacza brak limitu.',
            ge=0,
            le=9223372036854775807,
        ),
    ] = None
    storage_limit_mb: Annotated[
        int | None,
        Field(
            description='Maksymalna przestrzeń dyskowa klubu (MB). Brak wartości oznacza brak limitu.',
            ge=0,
            le=9223372036854775807,
        ),
    ] = None
    contact_email: Annotated[EmailStr, Field(max_length=254, title='Email kontaktowy')]
    website: Annotated[Website | Website1 | None, Field(title='Strona klubu')] = None
    contact_phone: Annotated[str, Field(max_length=20, title='Telefon kontaktowy')]
    location: Annotated[str, Field(max_length=255, title='Lokalizacja')]
    closed_mon: bool | None = None
    closed_tue: bool | None = None
    closed_wed: bool | None = None
    closed_thu: bool | None = None
    closed_fri: bool | None = None
    closed_sat: bool | None = None
    closed_sun: bool | None = None
    training_hour_price: Annotated[
        Decimal | None, Field(pattern='^-?\\d{0,6}(?:\\.\\d{0,2})?$')
    ] = None


class DayTypeEnum(StrEnum):
    weekday = 'weekday'
    weekend = 'weekend'


class DraftEmail(BaseModel):
    id: int
    sender: int
    sender_name: str
    recipients: list[int]
    attachments: list[Attachment]
    attachments_upload: list[AnyUrl] | None = None
    reply_to: int | None = None
    replies: str
    is_starred_by: list[int] | None = None
    is_read_by: list[int] | None = None
    is_deleted_by: list[int] | None = None
    is_draft_by: list[int] | None = None
    is_archived_by: list[int] | None = None
    subject: str | None = None
    body: str | None = None
    sent_at: AwareDatetime
    is_sent: bool | None = None


class DraftEmailRequest(BaseModel):
    recipients: list[int]
    attachments_upload: list[bytes] | None = None
    reply_to: int | None = None
    is_starred_by: list[int] | None = None
    is_read_by: list[int] | None = None
    is_deleted_by: list[int] | None = None
    is_draft_by: list[int] | None = None
    is_archived_by: list[int] | None = None
    subject: str | None = None
    body: str | None = None
    is_sent: bool | None = None


class Email(BaseModel):
    id: int
    sender: int
    sender_name: str
    recipients: list[int]
    attachments: list[Attachment]
    attachments_upload: list[AnyUrl] | None = None
    reply_to: int | None = None
    replies: str
    is_starred_by: list[int] | None = None
    is_read_by: list[int] | None = None
    is_deleted_by: list[int] | None = None
    is_draft_by: list[int] | None = None
    is_archived_by: list[int] | None = None
    subject: Annotated[str | None, Field(max_length=255)] = None
    body: str | None = None
    sent_at: AwareDatetime
    is_sent: bool | None = None


class EmailRequest(BaseModel):
    recipients: list[int]
    attachments_upload: list[bytes] | None = None
    reply_to: int | None = None
    is_starred_by: list[int] | None = None
    is_read_by: list[int] | None = None
    is_deleted_by: list[int] | None = None
    is_draft_by: list[int] | None = None
    is_archived_by: list[int] | None = None
    subject: Annotated[str | None, Field(max_length=255)] = None
    body: str | None = None
    is_sent: bool | None = None


class KindEnum(StrEnum):
    closed = 'closed'
    reserved = 'reserved'


class PaidViaEnum(StrEnum):
    blik = 'blik'


class ParentTrainingPaymentStatusEnum(StrEnum):
    unpaid = 'unpaid'
    paid = 'paid'
    pay_in_club = 'pay_in_club'
    payed_in_club = 'payed_in_club'


class ExternalLink4(RootModel[AnyUrl | None]):
    root: AnyUrl | None = None


class ExternalLink5(RootModel[str | None]):
    root: Annotated[str | None, Field(max_length=0)] = None


class PatchedAktualnosciThreadUpdateRequest(BaseModel):
    title: Annotated[str | None, Field(max_length=200)] = None
    content: Annotated[str | None, Field(min_length=1)] = None
    external_link: ExternalLink4 | ExternalLink5 | None = None


class PatchedClubCalendarEventRequest(BaseModel):
    title: Annotated[str | None, Field(max_length=160, min_length=1)] = None
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None
    all_day: bool | None = None


class PatchedClubPhotoRequest(BaseModel):
    image: bytes | None = None
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None


class Website2(RootModel[AnyUrl | None]):
    root: Annotated[AnyUrl | None, Field(title='Strona klubu')] = None


class Website3(RootModel[str | None]):
    root: Annotated[str | None, Field(max_length=0, title='Strona klubu')] = None


class PatchedClubProfileRequest(BaseModel):
    logo: bytes | None = None
    upload_photos: list[bytes] | None = None
    opening_time_mon: time | None = None
    closing_time_mon: time | None = None
    opening_time_tue: time | None = None
    closing_time_tue: time | None = None
    opening_time_wed: time | None = None
    closing_time_wed: time | None = None
    opening_time_thu: time | None = None
    closing_time_thu: time | None = None
    opening_time_fri: time | None = None
    closing_time_fri: time | None = None
    opening_time_sat: time | None = None
    closing_time_sat: time | None = None
    opening_time_sun: time | None = None
    closing_time_sun: time | None = None
    name: Annotated[
        str | None, Field(max_length=100, min_length=1, title='Nazwa klubu')
    ] = None
    user_limit: Annotated[
        int | None,
        Field(
            description='Maksymalna liczba użytkowników klubu. Brak wartości oznacza brak limitu.',
            ge=0,
            le=9223372036854775807,
        ),
    ] = None
    storage_limit_mb: Annotated[
        int | None,
        Field(
            description='Maksymalna przestrzeń dyskowa klubu (MB). Brak wartości oznacza brak limitu.',
            ge=0,
            le=9223372036854775807,
        ),
    ] = None
    contact_email: Annotated[
        EmailStr | None, Field(max_length=254, min_length=1, title='Email kontaktowy')
    ] = None
    website: Annotated[Website2 | Website3 | None, Field(title='Strona klubu')] = None
    contact_phone: Annotated[
        str | None, Field(max_length=20, min_length=1, title='Telefon kontaktowy')
    ] = None
    location: Annotated[
        str | None, Field(max_length=255, min_length=1, title='Lokalizacja')
    ] = None
    closed_mon: bool | None = None
    closed_tue: bool | None = None
    closed_wed: bool | None = None
    closed_thu: bool | None = None
    closed_fri: bool | None = None
    closed_sat: bool | None = None
    closed_sun: bool | None = None
    training_hour_price: Annotated[
        Decimal | None, Field(pattern='^-?\\d{0,6}(?:\\.\\d{0,2})?$')
    ] = None


class PatchedDraftEmailRequest(BaseModel):
    recipients: list[int] | None = None
    attachments_upload: list[bytes] | None = None
    reply_to: int | None = None
    is_starred_by: list[int] | None = None
    is_read_by: list[int] | None = None
    is_deleted_by: list[int] | None = None
    is_draft_by: list[int] | None = None
    is_archived_by: list[int] | None = None
    subject: str | None = None
    body: str | None = None
    is_sent: bool | None = None


class Email1(RootModel[str]):
    root: Annotated[str, Field(max_length=0)]


class PatchedParentChildUpdateRequest(BaseModel):
    phone: str | None = None
    profile_photo: bytes | None = None
    email: EmailStr | Email1 | None = None


class PatchedSportObjectExtraRequest(BaseModel):
    name: Annotated[str | None, Field(max_length=120, min_length=1)] = None
    amount: Annotated[Decimal | None, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')] = (
        None
    )


class PatchedSportObjectPhotoRequest(BaseModel):
    image: bytes | None = None
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None


class PatchedSportObjectPriceRequest(BaseModel):
    day_type: DayTypeEnum | None = None
    start_time: time | None = None
    end_time: time | None = None
    price: Annotated[Decimal | None, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')] = (
        None
    )


class PatchedSportObjectSpecialDayRequest(BaseModel):
    start_date: date | None = None
    end_date: date | None = None
    start_time: time | None = None
    end_time: time | None = None
    kind: KindEnum | None = None
    label: Annotated[str | None, Field(max_length=255)] = None
    notes: str | None = None


class ReservationId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class PatchedTrainingCalendarEventRequest(BaseModel):
    title: Annotated[str | None, Field(max_length=160, min_length=1)] = None
    group_id: int | None = None
    sport_object_id: int | None = None
    reservation_id: int | None = None
    reservation_ids: list[ReservationId] | None = None
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None
    notes: str | None = None


class PlayerId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class PatchedTrainingGroupRequest(BaseModel):
    name: Annotated[str | None, Field(max_length=100, min_length=1)] = None
    max_members: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    age_range: Annotated[str | None, Field(max_length=80)] = None
    description: str | None = None
    training_type_id: int | None = None
    coach_id: int | None = None
    player_ids: list[PlayerId] | None = None


class PatchedUserProfileUpdateRequest(BaseModel):
    email: Annotated[EmailStr | None, Field(min_length=1)] = None
    abonament: Annotated[str | None, Field(min_length=1)] = None
    user_type: Annotated[str | None, Field(min_length=1)] = None


class PaymentStatusEnum(StrEnum):
    unpaid = 'unpaid'
    pay_in_club = 'pay_in_club'
    paid = 'paid'


class Permission(BaseModel):
    id: int
    code: str
    label: str


class PermissionsEnum(StrEnum):
    aktualnosci_dodawanie_watku = 'aktualnosci_dodawanie_watku'
    aktualnosci_edycja_watku = 'aktualnosci_edycja_watku'
    aktualnosci_komentowanie = 'aktualnosci_komentowanie'
    komunikacja = 'komunikacja'
    zarzadzanie_klubem = 'zarzadzanie_klubem'
    zarzadzanie_rezerwacjami = 'zarzadzanie_rezerwacjami'
    rezerwacje = 'rezerwacje'
    kalendarz_klubowy_zarzadzanie = 'kalendarz_klubowy_zarzadzanie'
    kalendarz_klubowy_ogladanie = 'kalendarz_klubowy_ogladanie'
    strefa_trenera_odczyt = 'strefa_trenera_odczyt'
    strefa_trenera_zapis = 'strefa_trenera_zapis'
    strefa_trenera_menu = 'strefa_trenera_menu'
    strefa_rodzica_pokaz_menu = 'strefa_rodzica_pokaz_menu'
    strefa_rodzica_odczyt = 'strefa_rodzica_odczyt'
    strefa_rodzica_zapis = 'strefa_rodzica_zapis'
    platnosci_zajec_pokaz = 'platnosci_zajec_pokaz'
    platnosci_zajec_edycja = 'platnosci_zajec_edycja'
    kalendarz_zajec_odczyt = 'kalendarz_zajec_odczyt'
    kalendarz_zajec_menu = 'kalendarz_zajec_menu'


class Role(BaseModel):
    id: int
    code: str
    label: str
    description: str
    default_permissions: str
    default_permission_labels: str


class RolesEnum(StrEnum):
    administrator = 'administrator'
    prezes = 'prezes'
    trener = 'trener'
    zawodnik = 'zawodnik'
    rodzic = 'rodzic'
    skarbnik = 'skarbnik'
    recepcja = 'recepcja'
    rekreacja = 'rekreacja'
    gosc = 'gosc'


class SportObjectExtra(BaseModel):
    id: int
    sport_object: int
    name: Annotated[str, Field(max_length=120)]
    amount: Annotated[Decimal, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SportObjectExtraRequest(BaseModel):
    name: Annotated[str, Field(max_length=120, min_length=1)]
    amount: Annotated[Decimal, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')]


class SportObjectPhoto(BaseModel):
    id: int
    image: AnyUrl
    image_url: str
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    created_at: AwareDatetime


class SportObjectPhotoRequest(BaseModel):
    image: bytes
    position: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None


class SportObjectPrice(BaseModel):
    id: int
    sport_object: int
    day_type: DayTypeEnum | None = None
    start_time: time
    end_time: time
    price: Annotated[Decimal, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SportObjectPriceRequest(BaseModel):
    day_type: DayTypeEnum | None = None
    start_time: time
    end_time: time
    price: Annotated[Decimal, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')]


class SportObjectReservationStatusEnum(StrEnum):
    pending = 'pending'
    confirmed = 'confirmed'
    cancelled = 'cancelled'


class SportObjectSpecialDay(BaseModel):
    id: int
    sport_object: int
    start_date: date
    end_date: date
    start_time: time | None = None
    end_time: time | None = None
    kind: KindEnum | None = None
    label: Annotated[str | None, Field(max_length=255)] = None
    notes: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SportObjectSpecialDayRequest(BaseModel):
    start_date: date
    end_date: date
    start_time: time | None = None
    end_time: time | None = None
    kind: KindEnum | None = None
    label: Annotated[str | None, Field(max_length=255)] = None
    notes: str | None = None


class TokenRefresh(BaseModel):
    access: str


class TokenRefreshRequest(BaseModel):
    refresh: Annotated[str, Field(min_length=1)]


class TrainingCalendarEvent(BaseModel):
    id: int
    title: Annotated[str, Field(max_length=160)]
    group: Annotated[int | None, Field(...)]
    group_name: str
    sport_object: Annotated[int | None, Field(...)]
    sport_object_name: str
    sport_object_location: str
    trainer_price_per_hour: str
    object_price_per_hour: str
    child_price_per_hour: str
    group_members_count: str
    reservation: Annotated[int | None, Field(...)]
    reservation_ids: list[ReservationId] | None = None
    start_time: AwareDatetime
    end_time: AwareDatetime
    notes: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class TrainingCalendarEventRequest(BaseModel):
    title: Annotated[str, Field(max_length=160, min_length=1)]
    group_id: int | None = None
    sport_object_id: int | None = None
    reservation_id: int | None = None
    reservation_ids: list[ReservationId] | None = None
    start_time: AwareDatetime
    end_time: AwareDatetime
    notes: str | None = None


class TrainingGroupRequest(BaseModel):
    name: Annotated[str, Field(max_length=100, min_length=1)]
    max_members: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    age_range: Annotated[str | None, Field(max_length=80)] = None
    description: str | None = None
    training_type_id: int | None = None
    coach_id: int | None = None
    player_ids: list[PlayerId] | None = None


class TrainingMember(BaseModel):
    id: int
    first_name: Annotated[str | None, Field(max_length=50, title='Imię')] = None
    last_name: Annotated[str | None, Field(max_length=50, title='Nazwisko')] = None
    full_name: str
    email: Annotated[EmailStr, Field(max_length=254)]
    phone: Annotated[str | None, Field(max_length=20, title='Telefon')] = None
    roles: str


class TrainingMemberRequest(BaseModel):
    first_name: Annotated[str | None, Field(max_length=50, title='Imię')] = None
    last_name: Annotated[str | None, Field(max_length=50, title='Nazwisko')] = None
    email: Annotated[EmailStr, Field(max_length=254, min_length=1)]
    phone: Annotated[str | None, Field(max_length=20, title='Telefon')] = None


class TrainingType(BaseModel):
    id: int
    name: Annotated[str, Field(max_length=120)]
    price_per_hour: Annotated[
        Decimal | None, Field(pattern='^-?\\d{0,6}(?:\\.\\d{0,2})?$')
    ] = None
    is_active: bool | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class TrainingTypeRequest(BaseModel):
    name: Annotated[str, Field(max_length=120, min_length=1)]
    price_per_hour: Annotated[
        Decimal | None, Field(pattern='^-?\\d{0,6}(?:\\.\\d{0,2})?$')
    ] = None
    is_active: bool | None = None


class TypeEnum(StrEnum):
    tennis_court = 'tennis_court'
    fitness_studio = 'fitness_studio'
    gym = 'gym'
    sports_hall = 'sports_hall'
    football_pitch = 'football_pitch'
    swimming_pool = 'swimming_pool'
    other = 'other'


class ApiAktualnosciThreadsGetResponse(RootModel[list[AktualnosciThread]]):
    root: list[AktualnosciThread]


class ApiClubCalendarEventsGetResponse(RootModel[list[ClubCalendarEvent]]):
    root: list[ClubCalendarEvent]


class ApiClubPermissionsGetResponse(RootModel[list[Permission]]):
    root: list[Permission]


class ApiClubRolesGetResponse(RootModel[list[Role]]):
    root: list[Role]


class Action(StrEnum):
    mark_as_read = 'mark_as_read'
    mark_as_unread = 'mark_as_unread'
    star = 'star'
    unstar = 'unstar'
    delete = 'delete'
    restore = 'restore'
    mark_as_draft = 'mark_as_draft'
    mark_as_sent = 'mark_as_sent'
    archive = 'archive'
    unarchive = 'unarchive'


class ApiEmailsIdStatusPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: Annotated[Action, Field(examples=['mark_as_read'])]


class ApiEmailsDeletedGetResponse(RootModel[list[Email]]):
    root: list[Email]


class ApiEmailsDraftsGetResponse(RootModel[list[DraftEmail]]):
    root: list[DraftEmail]


class ApiEmailsInboxGetResponse(RootModel[list[Email]]):
    root: list[Email]


class ApiEmailsOutboxGetResponse(RootModel[list[Email]]):
    root: list[Email]


class ApiEmailsStarredGetResponse(RootModel[list[Email]]):
    root: list[Email]


class ApiPaymentsManagementTrainingPaymentsGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class ApiPaymentsManagementTrainingPaymentsMarkPaidPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    child_id: Annotated[int, Field(examples=[10])]
    group_id: Annotated[int | None, Field(examples=[5])] = None
    month: Annotated[str, Field(description='YYYY-MM', examples=['2026-07'])]


class Format(StrEnum):
    json = 'json'
    yaml = 'yaml'


class Lang(StrEnum):
    af = 'af'
    ar = 'ar'
    ar_dz = 'ar-dz'
    ast = 'ast'
    az = 'az'
    be = 'be'
    bg = 'bg'
    bn = 'bn'
    br = 'br'
    bs = 'bs'
    ca = 'ca'
    ckb = 'ckb'
    cs = 'cs'
    cy = 'cy'
    da = 'da'
    de = 'de'
    dsb = 'dsb'
    el = 'el'
    en = 'en'
    en_au = 'en-au'
    en_gb = 'en-gb'
    eo = 'eo'
    es = 'es'
    es_ar = 'es-ar'
    es_co = 'es-co'
    es_mx = 'es-mx'
    es_ni = 'es-ni'
    es_ve = 'es-ve'
    et = 'et'
    eu = 'eu'
    fa = 'fa'
    fi = 'fi'
    fr = 'fr'
    fy = 'fy'
    ga = 'ga'
    gd = 'gd'
    gl = 'gl'
    he = 'he'
    hi = 'hi'
    hr = 'hr'
    hsb = 'hsb'
    ht = 'ht'
    hu = 'hu'
    hy = 'hy'
    ia = 'ia'
    id = 'id'
    ig = 'ig'
    io = 'io'
    is_ = 'is'
    it = 'it'
    ja = 'ja'
    ka = 'ka'
    kab = 'kab'
    kk = 'kk'
    km = 'km'
    kn = 'kn'
    ko = 'ko'
    ky = 'ky'
    lb = 'lb'
    lt = 'lt'
    lv = 'lv'
    mk = 'mk'
    ml = 'ml'
    mn = 'mn'
    mr = 'mr'
    ms = 'ms'
    my = 'my'
    nb = 'nb'
    ne = 'ne'
    nl = 'nl'
    nn = 'nn'
    os = 'os'
    pa = 'pa'
    pl = 'pl'
    pt = 'pt'
    pt_br = 'pt-br'
    ro = 'ro'
    ru = 'ru'
    sk = 'sk'
    sl = 'sl'
    sq = 'sq'
    sr = 'sr'
    sr_latn = 'sr-latn'
    sv = 'sv'
    sw = 'sw'
    ta = 'ta'
    te = 'te'
    tg = 'tg'
    th = 'th'
    tk = 'tk'
    tr = 'tr'
    tt = 'tt'
    udm = 'udm'
    ug = 'ug'
    uk = 'uk'
    ur = 'ur'
    uz = 'uz'
    vi = 'vi'
    zh_hans = 'zh-hans'
    zh_hant = 'zh-hant'


class ApiSchemaGetResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ApiSportsObjectsObjectIdExtrasGetResponse(RootModel[list[SportObjectExtra]]):
    root: list[SportObjectExtra]


class ApiSportsObjectsObjectIdPricesGetResponse(RootModel[list[SportObjectPrice]]):
    root: list[SportObjectPrice]


class ApiSportsObjectsObjectIdSpecialDaysGetResponse(
    RootModel[list[SportObjectSpecialDay]]
):
    root: list[SportObjectSpecialDay]


class ApiSportsReservationsPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    sport_object: Annotated[int, Field(examples=[1])]
    start_time: Annotated[AwareDatetime, Field(examples=['2026-07-07T10:00:00Z'])]
    end_time: Annotated[AwareDatetime, Field(examples=['2026-07-07T11:00:00Z'])]
    title: Annotated[str | None, Field(examples=['Morning training reservation'])] = (
        None
    )
    notes: Annotated[str | None, Field(examples=['Optional details'])] = None
    status: Annotated[str | None, Field(examples=['booked'])] = None
    send_confirmation_email: Annotated[bool | None, Field(examples=[True])] = None


class ApiSportsReservationsReservationIdPatchRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    sport_object: Annotated[int | None, Field(examples=[1])] = None
    start_time: Annotated[
        AwareDatetime | None, Field(examples=['2026-07-07T10:00:00Z'])
    ] = None
    end_time: Annotated[
        AwareDatetime | None, Field(examples=['2026-07-07T11:00:00Z'])
    ] = None
    title: Annotated[str | None, Field(examples=['Updated reservation'])] = None
    notes: Annotated[str | None, Field(examples=['Updated notes'])] = None
    status: Annotated[str | None, Field(examples=['cancelled'])] = None
    send_cancellation_email: Annotated[bool | None, Field(examples=[True])] = None


class ApiSzkoleniaCalendarEventsGetResponse(RootModel[list[TrainingCalendarEvent]]):
    root: list[TrainingCalendarEvent]


class ApiSzkoleniaCoachesGetResponse(RootModel[list[TrainingMember]]):
    root: list[TrainingMember]


class ApiSzkoleniaManagementSettingsGetResponse(BaseModel):
    training_hour_price: Annotated[str | None, Field(examples=['120.00'])] = None


class ApiSzkoleniaManagementTrainingTypesGetResponse(RootModel[list[TrainingType]]):
    root: list[TrainingType]


class ApiSzkoleniaManagementTrainingTypesTypeIdPatchRequest(BaseModel):
    name: Annotated[str | None, Field(examples=['Technical training'])] = None
    price_per_hour: Annotated[str | None, Field(examples=['90.00'])] = None
    training_hour_price: Annotated[str | None, Field(examples=['120.00'])] = None


class ApiSzkoleniaMyCalendarGetResponse(RootModel[list[TrainingCalendarEvent]]):
    root: list[TrainingCalendarEvent]


class ApiSzkoleniaParentZoneCalendarGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class ApiSzkoleniaParentZoneCalendarMonthPayInClubPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    month: Annotated[
        str, Field(description='Month in YYYY-MM format', examples=['2026-07'])
    ]


class ApiSzkoleniaParentZoneCalendarMonthPayOnlinePostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    month: Annotated[
        str, Field(description='Month in YYYY-MM format', examples=['2026-07'])
    ]


class ApiSzkoleniaParentZoneChildrenGetResponse(RootModel[list[dict[str, Any]]]):
    root: list[dict[str, Any]]


class ApiSzkoleniaParentZoneChildrenChildIdPatchResponse(BaseModel):
    pass


class Method(StrEnum):
    club = 'club'
    blik = 'blik'


class ApiSzkoleniaParentZonePaymentsPaymentIdPayPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: Annotated[Method, Field(examples=['blik'])]


class ApiSzkoleniaPlayersGetResponse(RootModel[list[TrainingMember]]):
    root: list[TrainingMember]


class ApiSzkoleniaRecreationalPlayersGetResponse(RootModel[list[TrainingMember]]):
    root: list[TrainingMember]


class ApiSzkoleniaTrainingTypesGetResponse(RootModel[list[TrainingType]]):
    root: list[TrainingType]


class ApiUserManagementAuthenticatedPasswordResetPostRequest(BaseModel):
    password: Annotated[
        str,
        Field(
            description='New password for the authenticated user.',
            examples=['test_password'],
        ),
    ]


class ApiUserManagementLegalAcceptPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accept_terms: Annotated[bool, Field(examples=[True])]
    accept_privacy_policy: Annotated[bool, Field(examples=[True])]


class ApiUserManagementPasswordResetPostRequest(BaseModel):
    email: Annotated[
        EmailStr,
        Field(
            description='Email address associated with the account',
            examples=['admin.club@test.local'],
        ),
    ]


class ApiUserManagementPasswordResetConfirmTokenPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    password: Annotated[
        str, Field(description='New password for the user.', examples=['test_password'])
    ]


class ApiUserManagementRegisterPostRequest(BaseModel):
    email: Annotated[EmailStr, Field(examples=['admin.club@test.local'])]
    password: Annotated[str, Field(examples=['test_password'])]
    accept_terms: Annotated[bool, Field(examples=[True])]
    accept_privacy_policy: Annotated[bool, Field(examples=[True])]
    abonament: Annotated[str | None, Field(examples=['basic'])] = None


class ApiUserManagementResendActivationPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    email: Annotated[EmailStr, Field(examples=['admin.club@test.local'])]


class ApiUserManagementTokenPostRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    username: str
    password: str


class ApiUserManagementTokenPostResponse(BaseModel):
    refresh: Annotated[str | None, Field(examples=['refresh_token'])] = None
    access: Annotated[str | None, Field(examples=['access_token'])] = None


class ApiUserManagementTokenPostResponse1(BaseModel):
    detail: Annotated[
        str | None,
        Field(examples=['No active account found with the given credentials']),
    ] = None


class ApiUserManagementTokenPostResponse2(BaseModel):
    detail: Annotated[str | None, Field(examples=['Internal server error.'])] = None


class Member(BaseModel):
    id: int
    email: EmailStr
    roles: list[RolesEnum] | None = None
    permissions: list[PermissionsEnum] | None = None
    children: list[int] | None = None
    username: str
    has_login_account: str
    uses_placeholder_email: str
    parents: str
    parents_details: str
    profile_photo_url: str
    first_name: Annotated[str | None, Field(max_length=50, title='Imię')] = None
    last_name: Annotated[str | None, Field(max_length=50, title='Nazwisko')] = None
    phone: Annotated[str | None, Field(max_length=20, title='Telefon')] = None
    profile_photo: AnyUrl | None = None
    profile: int | None = None


class MemberRequest(BaseModel):
    email: Annotated[EmailStr, Field(min_length=1)]
    roles: list[RolesEnum] | None = None
    permissions: list[PermissionsEnum] | None = None
    children: list[int] | None = None
    first_name: Annotated[str | None, Field(max_length=50, title='Imię')] = None
    last_name: Annotated[str | None, Field(max_length=50, title='Nazwisko')] = None
    phone: Annotated[str | None, Field(max_length=20, title='Telefon')] = None
    profile_photo: bytes | None = None
    profile: int | None = None


class ParentTrainingPayment(BaseModel):
    id: int
    title: Annotated[str | None, Field(max_length=160)] = None
    amount: Annotated[Decimal, Field(pattern='^-?\\d{0,8}(?:\\.\\d{0,2})?$')]
    currency: Annotated[str | None, Field(max_length=8)] = None
    due_date: date | None = None
    status: ParentTrainingPaymentStatusEnum
    status_label: str
    paid_via: PaidViaEnum
    paid_via_label: str
    paid_at: Annotated[AwareDatetime | None, Field(...)]
    notes: str | None = None
    child: int
    child_name: str
    group: int | None = None
    group_name: str
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PatchedMemberRequest(BaseModel):
    email: Annotated[EmailStr | None, Field(min_length=1)] = None
    roles: list[RolesEnum] | None = None
    permissions: list[PermissionsEnum] | None = None
    children: list[int] | None = None
    first_name: Annotated[str | None, Field(max_length=50, title='Imię')] = None
    last_name: Annotated[str | None, Field(max_length=50, title='Nazwisko')] = None
    phone: Annotated[str | None, Field(max_length=20, title='Telefon')] = None
    profile_photo: bytes | None = None
    profile: int | None = None


class PatchedSportObjectRequest(BaseModel):
    name: Annotated[str | None, Field(max_length=120, min_length=1)] = None
    type: TypeEnum | None = None
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    opening_time: time | None = None
    closing_time: time | None = None
    min_reservation_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    max_recurring_days: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = (
        None
    )
    cancellation_window_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    belongs_to_club: bool | None = None
    pay_in_club_only: bool | None = None
    is_active: bool | None = None
    upload_photos: list[bytes] | None = None


class SportObject(BaseModel):
    id: int
    club: int
    name: Annotated[str, Field(max_length=120)]
    type: TypeEnum | None = None
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    opening_time: time | None = None
    closing_time: time | None = None
    min_reservation_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    max_recurring_days: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = (
        None
    )
    cancellation_window_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    belongs_to_club: bool | None = None
    pay_in_club_only: bool | None = None
    is_active: bool | None = None
    special_days: list[SportObjectSpecialDay]
    prices: list[SportObjectPrice]
    extras: list[SportObjectExtra]
    photos: list[SportObjectPhoto]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class SportObjectRequest(BaseModel):
    name: Annotated[str, Field(max_length=120, min_length=1)]
    type: TypeEnum | None = None
    description: str | None = None
    location: Annotated[str | None, Field(max_length=255)] = None
    opening_time: time | None = None
    closing_time: time | None = None
    min_reservation_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    max_recurring_days: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = (
        None
    )
    cancellation_window_minutes: Annotated[
        int | None, Field(ge=0, le=9223372036854775807)
    ] = None
    belongs_to_club: bool | None = None
    pay_in_club_only: bool | None = None
    is_active: bool | None = None
    upload_photos: list[bytes] | None = None


class SportObjectReservation(BaseModel):
    id: int
    sport_object: int
    reserved_by: Annotated[int | None, Field(...)]
    reserved_by_name: str
    start_time: AwareDatetime
    end_time: AwareDatetime
    status: SportObjectReservationStatusEnum | None = None
    payment_status: PaymentStatusEnum | None = None
    extras: list[int] | None = None
    recurring_weeks: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    recurring_weekdays: Any | None = None
    notes: str | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class TrainingGroup(BaseModel):
    id: int
    name: Annotated[str, Field(max_length=100)]
    max_members: Annotated[int | None, Field(ge=0, le=9223372036854775807)] = None
    age_range: Annotated[str | None, Field(max_length=80)] = None
    description: str | None = None
    training_type: str
    coach: TrainingMember
    players: list[TrainingMember]
    created_at: AwareDatetime
    updated_at: AwareDatetime


class ApiClubMembersGetResponse(RootModel[list[Member]]):
    root: list[Member]


class ApiClubMembersMemberIdGetResponse(RootModel[list[Member]]):
    root: list[Member]


class ApiSportsObjectsGetResponse(RootModel[list[SportObject]]):
    root: list[SportObject]


class ApiSportsReservationsGetResponse(RootModel[list[SportObjectReservation]]):
    root: list[SportObjectReservation]


class ApiSzkoleniaGroupsGetResponse(RootModel[list[TrainingGroup]]):
    root: list[TrainingGroup]


class ApiSzkoleniaParentZonePaymentsGetResponse(RootModel[list[ParentTrainingPayment]]):
    root: list[ParentTrainingPayment]
